import curses

COLOR_BLACK = curses.COLOR_BLACK
COLOR_WHITE = curses.COLOR_WHITE
COLOR_RED = curses.COLOR_RED
COLOR_GREEN = curses.COLOR_GREEN
COLOR_BLUE = curses.COLOR_BLUE
COLOR_YELLOW = curses.COLOR_YELLOW

BOLD = curses.A_BOLD
REVERSE = curses.A_REVERSE
UNDERLINE = curses.A_UNDERLINE
